import type { Metadata } from "next";
import "./globals.css";
// import ClientWrapper from "@/components/ClientWrapper";  
import Header from "@/components/layouts/Header";

export const metadata: Metadata = {
  title: "Binary Brains",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased"
        style={{ fontFamily: 'poppins' }}
        suppressHydrationWarning
      >
        {/* <ClientWrapper> */}
          <Header />
          {children}
        {/* </ClientWrapper> */}
      </body>
    </html>
  );
}
